### ISSUE TITLE
마크다운 # 태그 사용시 주의할 점

### ISSUE THREAD

**Issue by JSPlike** [JSPlike/OpenSource#11]
마크다운 # 태그 사용시 주의할 점이

#### 하고 공백하고 글 입력 해야합니다.

ex)
##[MySQL]  X
## [MySQL]  O

참고하시고 궁금한점 댓글 남겨주세요

**Comment by kimhe5623** [comment]
그리고 탭키로 글상자 만들 때도 위에 공백이 있어야 합니다~~~

ex)
hello
              <- 이처럼 공백이 있어야 글상자가 생겨요~
[tab]hello

**Comment by JSPlike** [comment]
오키 근데 탭보다 난 

"```"
이거
```
app.query(function(res, req) {});
```
가 편하드라? 간단한 코드 한줄 입력시에는

**Comment by kimhe5623** [comment]
\` 이거 편하긴 한데 mysql에서 사용하는 기호도 \`이 억기호라 중복되던데 해결방법 있나욤

**Comment by ge0126** [comment]
\ 쓰고 쓰면 된데요~~
