### ISSUE TITLE
수평선 사용

### ISSUE THREAD

**Issue by JSPlike** [JSPlike/OpenSource#13]
마크다운을 깔끔하게 작업하기위해 

수평선 사용을 권고 드립니다.

수평선을 사용하면 내용과 내용사이의 깔끔한 레이아웃을 관리할 수 있습니다.

수평선 만들기

1. "* * *"
* * *
2. "***"
***
3. "* * * * *"
* * * * * 
4. "- - -"
- - -

모두 사용가능합니다.~~^^

문의 사항 댓글로

**Comment by JSPlike** [comment]
위를 보면 살짝식 굵기가 다릅니다.

**Comment by kimhe5623** [comment]
감사합니다~

**Comment by JSPlike** [comment]
확인 완료
