### ISSUE TITLE
마크다운 사진 축소 하는 법

### ISSUE THREAD

**Issue by JSPlike** [JSPlike/OpenSource#8]
마크다운에서 사진 축소하는법 아는 사람 있나요?

**Comment by kimhe5623** [comment]
마크다운 파일에서 이미지의 크기를 조절하려면 {: width="" height=""} 부분을 추가한다. 숫자 뒤 px 단위를 붙이거나 생략할 수 있다.

![title](/img/myImg.png){: width="100" height="100"}

혹은, % 단위로 이미지 사이즈 조절이 가능하다. 주의할 점은 이미지 원본 크기가 100% 인 것이 아니라, 차지할 수 있는 전체 범위를 100%로 보는 듯하다. 가로, 세로 각각 100%로 나타내면 이미지는 아래와 같아진다.

![title](/img/myImg.png){: width="100%" height="100%"}

자세한 내용은 아래 링크 참고 하세요~
https://nachoi.github.io/studynote/2017/11/23/Github-resize-image.html

**Comment by JSPlike** [comment]
몇번의 이미지 사이즈 테스트 결과를 알려드릴게요 일단

title{: width="100px" height="100px"} 형식의 태그는 사용이 안됩니다.
html과 연동의 문제로 그러는 듯 합니다.
사용시 아래와 같게 됩니다.

![test](http://cfile6.uf.tistory.com/image/99DAF8335A27F985206DE9){:width="300px" height="200px"}

해결방법은

```
<img src="http://cfile6.uf.tistory.com/image/99DAF8335A27F985206DE9" width="300px" height="300px">"
```

아래의 이미지로 나오게 됩니다.

<img src="http://cfile6.uf.tistory.com/image/99DAF8335A27F985206DE9" width="300px" height="300px">


감사합니다.
