### ISSUE TITLE
오픈소스 채점기준에 따른 역할 분담

### ISSUE THREAD

**Issue by JSPlike** [JSPlike/OpenSource#9]
1. 오픈 소스 SW 선택의 이유 및 개요 (10)
2. 오픈 소스 SW에 대한 각 기능별 설명 (10)
3. 오픈 소스 SW 사용 설명에 대한 쉬운 이해가 가능한지 (10)
4. 사용 설명서 작성 중 발견한 오픈 소스 SW의 버그 및 원인 또는 사용 설명서 작성 중 느낀 기능 향상을 위한 제안 (10)
5. 각 팀원 별 협업을 증명할 자료 첨부(예: GitHub에 나와 있는 협업 히스토리) (20) 

1 - 효은, 가은
2 - 협업
3 - 협업
4 - 준영
5 - 협업

**Comment by kimhe5623** [comment]
알겠습니다~

**Comment by JSPlike** [comment]
오키 가은이도 확인하고

**Comment by ge0126** [comment]
넹 확인했습니당~~

**Comment by JSPlike** [comment]
모두 확인 완료
